  const currencyOptions = [
    { label: "AED United Arab Emirates Dirham", value: "د.إ" },
    { label: "AFN Afghan Afghani", value: "؋" },
    { label: "ALL Albanian Lek", value: "L" },
    { label: "AMD Armenian Dram", value: "֏" },
    { label: "ANG Netherlands Antillean Guilder", value: "ƒ" },
    { label: "AOA Angolan Kwanza", value: "Kz" },
    { label: "ARS Argentine Peso", value: "$" },
    { label: "AUD Australian Dollar", value: "A$" },
    { label: "AWG Aruban Florin", value: "ƒ" },
    { label: "AZN Azerbaijani Manat", value: "₼" },
    { label: "BAM Bosnia-Herzegovina Convertible Mark", value: "KM" },
    { label: "BBD Barbadian Dollar", value: "$" },
    { label: "BDT Bangladeshi Taka", value: "৳" },
    { label: "BGN Bulgarian Lev", value: "лв" },
    { label: "BHD Bahraini Dinar", value: ".د.ب" },
    { label: "BIF Burundian Franc", value: "FBu" },
    { label: "BMD Bermudian Dollar", value: "$" },
    { label: "BND Brunei Dollar", value: "$" },
    { label: "BOB Bolivian Boliviano", value: "Bs." },
    { label: "BRL Brazilian Real", value: "R$" },
    { label: "BSD Bahamian Dollar", value: "$" },
    { label: "BTN Bhutanese Ngultrum", value: "Nu." },
    { label: "BWP Botswana Pula", value: "P" },
    { label: "BYN Belarusian Ruble", value: "Br" },
    { label: "BZD Belize Dollar", value: "BZ$" },
    { label: "CAD Canadian Dollar", value: "C$" },
    { label: "CDF Congolese Franc", value: "FC" },
    { label: "CHF Swiss Franc", value: "CHF" },
    { label: "CLP Chilean Peso", value: "$" },
    { label: "CNY Chinese Yuan", value: "¥" },
    { label: "COP Colombian Peso", value: "$" },
    { label: "CRC Costa Rican Colón", value: "₡" },
    { label: "CUP Cuban Peso", value: "$" },
    { label: "CVE Cape Verdean Escudo", value: "$" },
    { label: "CZK Czech Koruna", value: "Kč" },
    { label: "DJF Djiboutian Franc", value: "Fdj" },
    { label: "DKK Danish Krone", value: "kr" },
    { label: "DOP Dominican Peso", value: "RD$" },
    { label: "DZD Algerian Dinar", value: "دج" },
    { label: "EGP Egyptian Pound", value: "£" },
    { label: "ERN Eritrean Nakfa", value: "Nkf" },
    { label: "ETB Ethiopian Birr", value: "Br" },
    { label: "EUR Euro", value: "€" },
    { label: "FJD Fijian Dollar", value: "$" },
    { label: "FKP Falkland Islands Pound", value: "£" },
    { label: "FOK Faroese Króna", value: "kr" },
    { label: "GBP British Pound Sterling", value: "£" },
    { label: "GEL Georgian Lari", value: "₾" },
    { label: "GGP Guernsey Pound", value: "£" },
    { label: "GHS Ghanaian Cedi", value: "₵" },
    { label: "GIP Gibraltar Pound", value: "£" },
    { label: "GMD Gambian Dalasi", value: "D" },
    { label: "GNF Guinean Franc", value: "FG" },
    { label: "GTQ Guatemalan Quetzal", value: "Q" },
    { label: "GYD Guyanese Dollar", value: "$" },
    { label: "HKD Hong Kong Dollar", value: "HK$" },
    { label: "HNL Honduran Lempira", value: "L" },
    { label: "HRK Croatian Kuna", value: "kn" },
    { label: "HTG Haitian Gourde", value: "G" },
    { label: "HUF Hungarian Forint", value: "Ft" },
    { label: "IDR Indonesian Rupiah", value: "Rp" },
    { label: "ILS Israeli New Shekel", value: "₪" },
    { label: "IMP Isle of Man Pound", value: "£" },
    { label: "INR Indian Rupee", value: "₹" },
    { label: "IQD Iraqi Dinar", value: "د.ع" },
    { label: "IRR Iranian Rial", value: "﷼" },
    { label: "ISK Icelandic Króna", value: "kr" },
    { label: "JEP Jersey Pound", value: "£" },
    { label: "JMD Jamaican Dollar", value: "J$" },
    { label: "JOD Jordanian Dinar", value: "د.ا" },
    { label: "JPY Japanese Yen", value: "¥" },
    { label: "KES Kenyan Shilling", value: "KSh" },
    { label: "KGS Kyrgyzstani Som", value: "сом" },
    { label: "KHR Cambodian Riel", value: "៛" },
    { label: "KID Kiribati Dollar", value: "$" },
    { label: "KMF Comorian Franc", value: "CF" },
    { label: "KRW South Korean Won", value: "₩" },
    { label: "KWD Kuwaiti Dinar", value: "د.ك" },
    { label: "KYD Cayman Islands Dollar", value: "$" },
    { label: "KZT Kazakhstani Tenge", value: "₸" },
    { label: "LAK Lao Kip", value: "₭" },
    { label: "LBP Lebanese Pound", value: "ل.ل" },
    { label: "LKR Sri Lankan Rupee", value: "Rs" },
    { label: "LRD Liberian Dollar", value: "$" },
    { label: "LSL Lesotho Loti", value: "L" },
    { label: "LYD Libyan Dinar", value: "ل.د" },
    { label: "MAD Moroccan Dirham", value: "د.م." },
    { label: "MDL Moldovan Leu", value: "L" },
    { label: "MGA Malagasy Ariary", value: "Ar" },
    { label: "MKD Macedonian Denar", value: "ден" },
    { label: "MMK Burmese Kyat", value: "K" },
    { label: "MNT Mongolian Tögrög", value: "₮" },
    { label: "MOP Macanese Pataca", value: "P" },
    { label: "MRU Mauritanian Ouguiya", value: "UM" },
    { label: "MUR Mauritian Rupee", value: "₨" },
    { label: "MVR Maldivian Rufiyaa", value: "Rf" },
    { label: "MWK Malawian Kwacha", value: "MK" },
    { label: "MXN Mexican Peso", value: "$" },
    { label: "MYR Malaysian Ringgit", value: "RM" },
    { label: "MZN Mozambican Metical", value: "MT" },
    { label: "NAD Namibian Dollar", value: "$" },
    { label: "NGN Nigerian Naira", value: "₦" },
    { label: "NIO Nicaraguan Córdoba", value: "C$" },
    { label: "NOK Norwegian Krone", value: "kr" },
    { label: "NPR Nepalese Rupee", value: "₨" },
    { label: "NZD New Zealand Dollar", value: "NZ$" },
    { label: "OMR Omani Rial", value: "﷼" },
    { label: "PAB Panamanian Balboa", value: "B/." },
    { label: "PEN Peruvian Sol", value: "S/." },
    { label: "PGK Papua New Guinean Kina", value: "K" },
    { label: "PHP Philippine Peso", value: "₱" },
    { label: "PKR Pakistani Rupee", value: "₨" },
    { label: "PLN Polish Złoty", value: "zł" },
    { label: "PYG Paraguayan Guaraní", value: "₲" },
    { label: "QAR Qatari Riyal", value: "﷼" },
    { label: "RON Romanian Leu", value: "lei" },
    { label: "RSD Serbian Dinar", value: "РСД" },
    { label: "RUB Russian Ruble", value: "₽" },
    { label: "RWF Rwandan Franc", value: "FRw" },
    { label: "SAR Saudi Riyal", value: "﷼" },
    { label: "SBD Solomon Islands Dollar", value: "$" },
    { label: "SCR Seychellois Rupee", value: "₨" },
    { label: "SDG Sudanese Pound", value: "ج.س." },
    { label: "SEK Swedish Krona", value: "kr" },
    { label: "SGD Singapore Dollar", value: "S$" },
    { label: "SHP Saint Helena Pound", value: "£" },
    { label: "SLL Sierra Leonean Leone", value: "Le" },
    { label: "SOS Somali Shilling", value: "S" },
    { label: "SRD Surinamese Dollar", value: "$" },
    { label: "SSP South Sudanese Pound", value: "£" },
    { label: "STN São Tomé and Príncipe Dobra", value: "Db" },
    { label: "SYP Syrian Pound", value: "£" },
    { label: "SZL Swazi Lilangeni", value: "E" },
    { label: "THB Thai Baht", value: "฿" },
    { label: "TJS Tajikistani Somoni", value: "ЅМ" },
    { label: "TMT Turkmenistani Manat", value: "m" },
    { label: "TND Tunisian Dinar", value: "د.ت" },
    { label: "TOP Tongan Paʻanga", value: "T$" },
    { label: "TRY Turkish Lira", value: "₺" },
    { label: "TTD Trinidad and Tobago Dollar", value: "TT$" },
    { label: "TVD Tuvaluan Dollar", value: "$" },
    { label: "TWD New Taiwan Dollar", value: "NT$" },
    { label: "TZS Tanzanian Shilling", value: "TSh" },
    { label: "UAH Ukrainian Hryvnia", value: "₴" },
    { label: "UGX Ugandan Shilling", value: "USh" },
    { label: "USD US Dollar", value: "$" },
    { label: "UYU Uruguayan Peso", value: "$U" },
    { label: "UZS Uzbekistani Soʻm", value: "soʻm" },
    { label: "VES Venezuelan Bolívar", value: "Bs.S" },
    { label: "VND Vietnamese Dong", value: "₫" },
    { label: "VUV Vanuatu Vatu", value: "VT" },
    { label: "WST Samoan Tala", value: "T" },
    { label: "XAF Central African CFA Franc", value: "FCFA" },
    { label: "XCD East Caribbean Dollar", value: "EC$" },
    { label: "XOF West African CFA Franc", value: "CFA" },
    { label: "XPF CFP Franc", value: "CFP" },
    { label: "YER Yemeni Rial", value: "﷼" },
    { label: "ZAR South African Rand", value: "R" },
    { label: "ZMW Zambian Kwacha", value: "ZK" },
    { label: "ZWL Zimbabwean Dollar", value: "Z$" }
  ];

  export default currencyOptions;